# Generated by Django 4.2.3 on 2023-10-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmmApmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(blank=True, max_length=2)),
                ('global_collection', models.CharField(blank=True, max_length=50)),
                ('filial', models.CharField(blank=True, max_length=50)),
                ('service_manager', models.CharField(blank=True, max_length=200)),
                ('sub_service', models.CharField(blank=True, max_length=200)),
                ('gestor_broker', models.CharField(blank=True, max_length=200)),
                ('monitor_resource', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('rol', models.CharField(blank=True, max_length=50)),
                ('name_device', models.CharField(blank=True, max_length=50)),
                ('ip_divice', models.CharField(blank=True, max_length=50)),
                ('type_configuration', models.CharField(blank=True, max_length=50)),
                ('item_configuration', models.CharField(blank=True, max_length=50)),
                ('alert_generation', models.CharField(blank=True, max_length=200)),
                ('metric_configuration', models.CharField(blank=True, max_length=200)),
                ('intervalo', models.CharField(blank=True, max_length=200)),
                ('alert_hours', models.CharField(blank=True, max_length=100)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('pot_major', models.CharField(blank=True, max_length=100)),
                ('op_major', models.CharField(blank=True, max_length=100)),
                ('critical', models.CharField(blank=True, max_length=100)),
                ('pot_critical', models.CharField(blank=True, max_length=100)),
                ('op_critical', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('impact', models.CharField(blank=True, max_length=500)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('spectrum', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField()),
                ('order_number_oc', models.CharField(blank=True, max_length=500)),
                ('maintenance', models.BooleanField(verbose_name=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'amm_apm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAmmApmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email_notification', models.CharField(max_length=500)),
                ('order_oc', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_amm_apm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAmmApmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isiries', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('subsistem', models.CharField(max_length=50)),
                ('instances', models.CharField(max_length=50)),
                ('instances_affectation', models.CharField(max_length=500)),
                ('name_menu', models.CharField(max_length=50)),
                ('group_rise', models.CharField(max_length=200)),
                ('id_divice', models.CharField(max_length=50)),
                ('menu_chksys', models.CharField(max_length=500)),
                ('maintenance', models.BooleanField()),
                ('status', models.BooleanField()),
                ('order_oc', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_amm_apm',
                'ordering': ['-created_at'],
            },
        ),
    ]
